# Generated by Django 2.0 on 2018-05-13 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('linkid', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('shortenURL', models.CharField(max_length=500, unique=True)),
                ('targetURL', models.CharField(max_length=500)),
            ],
        ),
    ]
