# Generated by Django 2.0 on 2018-05-14 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20180513_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='last_hit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
