# Generated by Django 2.0 on 2018-05-14 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_link_last_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 14, 15, 14, 55, 56834)),
        ),
        migrations.AlterField(
            model_name='link',
            name='last_hit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 14, 15, 14, 55, 56834)),
        ),
    ]
