# Generated by Django 2.0 on 2018-05-14 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_auto_20180514_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 14, 15, 35, 37, 849816)),
        ),
        migrations.AlterField(
            model_name='link',
            name='last_hit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 14, 15, 35, 37, 849816)),
        ),
    ]
