# Generated by Django 2.0 on 2018-05-14 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_auto_20180514_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='link',
            name='last_hit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
