# Generated by Django 2.0 on 2018-05-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_auto_20180514_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
